[tool.poetry]
name = "django_mfa_example"
version = "0.1.0"
description = "For PyGotham 2018"
authors = ["Collin Stedman <kronion@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
django = "^2.1"

[tool.poetry.dev-dependencies]
django-extensions = "^2.1"
